// Pack baked bodies (tools/bake_body.py output: <name>.json + <name>.bin) into src/assets/bodies.js.
// usage: node tools/pack_bodies.mjs <bakedDir> name [name...]
import fs from 'fs';
import path from 'path';
const [dir, ...names] = process.argv.slice(2);
const credits = JSON.parse(fs.readFileSync(path.join(dir, 'credits.json'), 'utf8'));
let out = '// Generated by tools/pack_bodies.mjs from baked body meshes. Do not edit by hand.\n';
out += `export const BODY_CREDITS = ${JSON.stringify(credits, null, 1)};\n`;
out += 'export const BODIES = {\n';
for (const n of names) {
  const meta = JSON.parse(fs.readFileSync(path.join(dir, n + '.json'), 'utf8'));
  const bin = fs.readFileSync(path.join(dir, n + '.bin')).toString('base64');
  out += `  ${n}: { meta: ${JSON.stringify(meta)}, data: '${bin}' },\n`;
}
out += '};\n';
fs.writeFileSync(new URL('../src/assets/bodies.js', import.meta.url), out);
console.log('wrote src/assets/bodies.js', (out.length / 1024).toFixed(0), 'KB');
